spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

# 받을 수 없는 프로퍼티를 넘기면 오류 처리함.
  jackson:
    deserialization:
      fail-on-unknown-properties: true